[package]
name = "cluedo-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.1"
rocket = { version = "0.5.1", features = ["json"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
strum = { version = "0.27.1", features = ["derive"] }
